### ISSUE TITLE
question

### ISSUE THREAD

**Issue by toshibochan** [KanyonKris/relay_board#3]
thanks for make great plugins.
how i can change what pin number i use for each zone?

thanks

toshi

**Comment by toshibochan** [comment]
i want just use pin 29,31,33,35,37

**Comment by KanyonKris** [comment]
Edit "relay_board.py" found in the plugins directory. Find the line below and change it to whatever pins and order you want.

relay_pins = ["11","12","13","15","16","18","22","7","3","5","24","26"]
