### ISSUE TITLE
Only 7 stations work

### ISSUE THREAD

**Issue by RWoerz** [KanyonKris/relay_board#4]
All fixed. I'm having a problem where only the first 7 stations work. When I configured 8 stations the last station doesn't work. It shows up but when I manually turn it on nothing happens. I know the relay works as I moved a working station wire over to it and it works fine.  Station 8 is on pin 7 right? Also after changing the number of stations to 10 still only 8 show up.  

Also on the Rpi I get the following error message whenever I turn on any of the stations.

Problem switching replays list index out of range 2
Problem switching replays list index out of range 3

Hope you can help my RainBird controller died yesterday and my lawn is going to be unhappy with me real soon. Thanks for the help.

**Comment by KanyonKris** [comment]
First, double check your wiring.  Relay 8 should be connected to pin 7 on the Raspberry Pi - https://github.com/KanyonKris/relay_board/wiki

Go to the Options page and make sure no Master is defined - https://github.com/Dan-in-CA/SIP/wiki/configure_master

Next let's see see if the problem is the Raspberry Pi pin 7 or relay 8. Swap relay wires 7 and 8.
Manually turn on station 7. If relay 8 turns on, something is wrong with pin 7 of the Raspberry Pi.  If relay 8 does not turn on, there is a problem with relay 8.

If there is a problem with pin 7 of the the Raspberry Pi, you can try a different pin to drive relay 8. Edit "relay_board.py", find this line:

relay_pins = ["11","12","13","15","16","18","22","7","3","5","24","26"]

change it to:

relay_pins = ["11","12","13","15","16","18","22","3","7","5","24","26"]

Which swaps pins 3 and 7. Save the file, stop running SIP and restart it.  Now connect relay 8 to pin 3. Hopefully relay 8 now works. If not, I'm out of ideas.

**Comment by RWoerz** [comment]
​
Thanks for getting back to me
​
. It turns out that pin 7 on my Rp
​i​
 is
​
dead
​
. I had tried editing the relay_board
​
but for some reason I wasn't able to save the changes. Permissions I'm
sure.
​

​
Because
I wasn't able to save my changes I'll just not use that zone. As for the
other errors I was getting they've disappeared as well. I did an OS update
in the middle of all this so that may have something to do with that.

I've spent some 40 years designing, building and fixing computers but I'm
new to Linux, Python and and the Raspberry Pi. It seems the pin layout was
brought to us by the people that designed the camel so I'm glad you used
pin numbers but at first is't a bit confusing. Probably old age more than
anything.

One thing that was also not obvious was how to extend the number of zones
pasted 8. I may have missed an easier solution but I finally used the
number of extension boards. Changing it in the relay board plugin should
somehow automagically change the global variable.

Another anomaly was whatever size I had my browser set to after changing
the number of stations from 8 to 10 the pulldown grayed out. Might have
some to do with my fount size and the width of the pulldown menu. After
changing the window size everything showed up again but was a bit
perplexing at first.
​ ​

It has always be my opinion that in the before time the people that
designed sprinkler controllers had no idea how to design an interface for
humans
.

Thanks again for the great innovative work
.
My son was involved for some time in writing add ons to the Kerbal Space
Program so I have some understanding of the commitment you're making.

It's all about the journey and mine has to continues as my grass isn't very
happy with me right now.

**Comment by KanyonKris** [comment]
For editing you need to be root so do this:

sudo nano relay_board.py

The number of zones (stations) is handled by the plugin, not the Options. I added a screen shot of the webpage to show this - https://github.com/KanyonKris/relay_board/wiki

Note that I ran into a bug:  When I started from a fresh install of SIP and used the PLUGINS | MANAGE PLUGINS to install relay_board, a new entry under PLUGINS is supposed to show up called RELAY BOARD, but it didn't. I had to shut down sip.py and go into the SIP/templates directory and change the owner and group from "root" to "pi", then restart sip.py and it showed up. These are the commands:

sudo chown pi relay_board.html
sudo chgrp pi relay_board.html

The plugin is supposed to change the number of zones/stations, but it's not. Thanks for reporting that, I'll look into it.

I'm not seeing the web page grayed out issue. It may be related to the number of zones/stations not changing. I'll key an eye out for this.

**Comment by RWoerz** [comment]
Thanks again for the help just wish I could do more to help.

**Comment by RWoerz** [comment]
Sorry for another question. I'm assuming the sip.sh somehow has to run at
startup. Where does it need to sit and what permissions does it need. I'm
sure it somehow tells me how to do it in the file I just don't get it,
sorry.

**Comment by RWoerz** [comment]
Also if you want me to go through the forum rather then email I can do that
too. Thanks again.

**Comment by RWoerz** [comment]
Sorry I found it on you startup page. I was looking everywhere else.
